### ISSUE TITLE
Encoding error in read_sheet

### ISSUE THREAD

**Issue by selesnow** [tidyverse/googlesheets4#56]
Hello!

I have trouble when i read sheet with russian (cyrillic) character on Windows.

I was create test spreadsheet - https://docs.google.com/spreadsheets/d/1V2kAi4RVWHVwnnblikfsE1KHs1DlWK1mmoFM1BvXEH8/edit#gid=0

![Exampe](http://img.netpeak.ua/alsey/157322067052_kiss_21kb.png)

But i get this data like:
```
Reading from 'Rus name - РўСѓС‚ РЅР°РІР·РІР°РЅРёРµ С‚Р°Р±Р»РёС†С‹'
Range "'list1'"
> print(head(ss_example))
# A tibble: 3 x 2
  col_1  col_2         
  <chr>  <chr>         
1 Р Р°Р· РђР»РµРєСЃРµР№
2 Р”РІР° РћР»РµРі      
3 РўСЂРё РџС‘С‚СЂ    
```

## REPREX

``` r
library(googlesheets4)

ss_example <-
  as_sheets_id("1V2kAi4RVWHVwnnblikfsE1KHs1DlWK1mmoFM1BvXEH8") %>%
  read_sheet(sheet = 1)
#> Using an auto-discovered, cached token.
#> To suppress this message, modify your code or options to clearly consent to the use of a cached token.
#> See gargle's "Non-interactive auth" vignette for more details:
#> https://gargle.r-lib.org/articles/non-interactive-auth.html
#> The googlesheets4 package is using a cached token for alsey.netpeak@gmail.com.
#> Auto-refreshing stale OAuth token.
#> Reading from 'Rus name - Р СћРЎС“РЎвЂљ Р Р…Р В°Р Р†Р В·Р Р†Р В°Р Р…Р С‘Р Вµ РЎвЂљР В°Р В±Р В»Р С‘РЎвЂ РЎвЂ№'
#> Range "'list1'"

print(head(ss_example))
#> # A tibble: 3 x 2
#>   col_1  col_2         
#>   <chr>  <chr>         
#> 1 Р В Р В°Р В· Р С’Р В»Р ВµР С”РЎРѓР ВµР в„–
#> 2 Р вЂќР Р†Р В° Р С›Р В»Р ВµР С–      
#> 3 Р СћРЎР‚Р С‘ Р СџРЎвЂРЎвЂљРЎР‚
```

<sup>Created on 2019-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.3 (2019-03-11)
#>  os       Windows Server x64          
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Europe/Helsinki             
#>  date     2019-11-08                  
#> 
#> - Packages --------------------------------------------------------------
#>  package       * version date       lib source        
#>  askpass         1.1     2019-01-13 [1] CRAN (R 3.5.3)
#>  assertthat      0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  backports       1.1.5   2019-10-02 [1] CRAN (R 3.5.3)
#>  callr           3.2.0   2019-03-15 [1] CRAN (R 3.5.3)
#>  cellranger      1.1.0   2016-07-27 [1] CRAN (R 3.5.3)
#>  cli             1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
#>  crayon          1.3.4   2017-09-16 [1] CRAN (R 3.5.3)
#>  curl            4.2     2019-09-24 [1] CRAN (R 3.5.3)
#>  desc            1.2.0   2018-05-01 [1] CRAN (R 3.5.3)
#>  devtools        2.0.2   2019-04-08 [1] CRAN (R 3.5.3)
#>  digest          0.6.22  2019-10-21 [1] CRAN (R 3.5.3)
#>  evaluate        0.13    2019-02-12 [1] CRAN (R 3.5.3)
#>  fansi           0.4.0   2018-10-05 [1] CRAN (R 3.5.3)
#>  fs              1.3.1   2019-05-06 [1] CRAN (R 3.5.3)
#>  gargle          0.4.0   2019-10-04 [1] CRAN (R 3.5.3)
#>  glue            1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  googlesheets4 * 0.1.0   2019-11-04 [1] CRAN (R 3.5.3)
#>  highr           0.8     2019-03-20 [1] CRAN (R 3.5.3)
#>  htmltools       0.3.6   2017-04-28 [1] CRAN (R 3.5.3)
#>  httr            1.4.1   2019-08-05 [1] CRAN (R 3.5.3)
#>  jsonlite        1.6     2018-12-07 [1] CRAN (R 3.5.3)
#>  knitr           1.23    2019-05-18 [1] CRAN (R 3.5.3)
#>  magrittr        1.5     2014-11-22 [1] CRAN (R 3.5.3)
#>  memoise         1.1.0   2017-04-21 [1] CRAN (R 3.5.3)
#>  openssl         1.4.1   2019-07-18 [1] CRAN (R 3.5.3)
#>  pillar          1.4.2   2019-06-29 [1] CRAN (R 3.5.3)
#>  pkgbuild        1.0.3   2019-03-20 [1] CRAN (R 3.5.3)
#>  pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 3.5.3)
#>  pkgload         1.0.2   2018-10-29 [1] CRAN (R 3.5.3)
#>  prettyunits     1.0.2   2015-07-13 [1] CRAN (R 3.5.3)
#>  processx        3.3.1   2019-05-08 [1] CRAN (R 3.5.3)
#>  ps              1.3.0   2018-12-21 [1] CRAN (R 3.5.3)
#>  purrr           0.3.3   2019-10-18 [1] CRAN (R 3.5.3)
#>  R6              2.4.0   2019-02-14 [1] CRAN (R 3.5.3)
#>  Rcpp            1.0.2   2019-07-25 [1] CRAN (R 3.5.3)
#>  remotes         2.0.4   2019-04-10 [1] CRAN (R 3.5.3)
#>  rlang           0.4.0   2019-06-25 [1] CRAN (R 3.5.3)
#>  rmarkdown       1.12    2019-03-14 [1] CRAN (R 3.5.3)
#>  rprojroot       1.3-2   2018-01-03 [1] CRAN (R 3.5.3)
#>  sessioninfo     1.1.1   2018-11-05 [1] CRAN (R 3.5.3)
#>  stringi         1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr         1.4.0   2019-02-10 [1] CRAN (R 3.5.3)
#>  tibble          2.1.3   2019-06-06 [1] CRAN (R 3.5.3)
#>  usethis         1.5.0   2019-04-07 [1] CRAN (R 3.5.3)
#>  utf8            1.1.4   2018-05-24 [1] CRAN (R 3.5.3)
#>  vctrs           0.2.0   2019-07-05 [1] CRAN (R 3.5.3)
#>  withr           2.1.2   2018-03-15 [1] CRAN (R 3.5.3)
#>  xfun            0.7     2019-05-14 [1] CRAN (R 3.5.3)
#>  yaml            2.2.0   2018-07-25 [1] CRAN (R 3.5.2)
#>  zeallot         0.1.0   2018-01-28 [1] CRAN (R 3.5.3)
#> 
#> [1] C:/Users/Alsey/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.3/library
```

</details>

**Comment by ramirobentes** [comment]
I'm having the same problem with words in brazilian portuguese (eg.: preço, fácil, ônus)

**Comment by Flavjack** [comment]
The same problem when i want import a cells with (°C) or coordinates 

Table:
![image](https://user-images.githubusercontent.com/7735493/68814165-647d5900-0678-11ea-91c9-2fb76b690eb8.png)

Result:

![image](https://user-images.githubusercontent.com/7735493/68814266-9db5c900-0678-11ea-89a4-414be3965a90.png)

**Comment by francisbarton** [comment]
I'm having the same problem. I found a closed issue that should solve it though: https://github.com/tidyverse/googlesheets4/issues/26 - you need the dev version of gargle.

**Comment by jennybc** [comment]
This is fixed in the development version of gargle as @francisbarton says. I will do a gargle release soon, but I need to fold a few more things into it (which are important for giving googlesheets4 edit/write capability).

So do:

```
devtools::install_github("r-lib/gargle")
```

and make sure to restart R.

**Comment by selesnow** [comment]
> This is fixed in the development version of gargle and has already been worked through here in issue #26, as @francisbarton says. I will do a gargle release soon, but I need to fold a few more things into it (which are important for giving googlesheets4 edit/write capability).
> 
> So do:
> 
> ```
> devtools::install_github("r-lib/gargle")
> ```
> 
> and make sure to restart R.

Jenny, thanks a lot, it's worked for me.

**Comment by abaranska09** [comment]
Hello everyone. Installing new version of gargle didn't resolve my problem. Did somebody have any idea what may be wrong?
After putting into console:
**read_sheet(deaths, range = "A1:F8")**

I get output:
**Reading from 'test_gsheet'
Range "A1:F8"
Error: is_string(ctype) is not TRUE**

Thanks for your help

**Comment by jennybc** [comment]
@abaranska09 I suggest that you double check you've done all of these things:

reinstalled gargle
reinstalled googlesheets4
**restarted R**

**Comment by Lithium1987** [comment]
Hello @jennybc 
I have a such problem as @selesnow 
And I followed your instructions to resolve this problem
But when I'm trying to install "gargle" package from github I'm receiving an error that downloaded file had non-zero exit status (‘C:/Users/userName/AppData/Local/Temp/2/Rtmp6pXbu7/file2678fb159b6/gargle_0.4.0.9002.tar.gz’ had non-zero exit status")
Is there a chance that I did something wrong?

**Comment by jennybc** [comment]
@VladKrenz Can you install other packages from GitHub? Test with another one that has no compiled code in it. My first theory is that you have a permissions problem. I'm pretty skeptical that this is specific to the gargle package.

**Comment by sjeangirard** [comment]
For those still facing the "Error: is_string(ctype) is not TRUE" after updating gargle and googlesheets4 and restarting R you can try to update purrr as well. 
I still had the error with purrr 0.2.5, when debugging I noticed that the error was coming from purrr::map2's line. 
Updating to purrr 0.3.3 fixed this issue for me.

**Comment by jhon-arias** [comment]
This worked for me:

**1. Remove ´googlesheets4´ from my R enviroment** 
**2.  install packages**
     `devtools::install_github("r-lib/gargle")`
     _- Which would you like to update?_
     _**- Select 3: None**_
     `install.packages("googlesheets4")`
**3. Restarted R**

**Comment by bwganblack** [comment]
@sjeangirard Good one. I  uninstalled purr 0.2.5 and reinstalled purr 0.3.4 and this fixed the error for me to.

**Comment by sam-watts** [comment]
+1 for updating purrr fixing "Error: is_string(ctype) is not TRUE". Should purrr 0.3.x be specified in Imports in the DESCRIPTION file of the development version so this is picked up automatically?

**Comment by sam-watts** [comment]
@jennybc 0.3.0 seems to be the minimum for purrr
